### ISSUE TITLE
How do you make mods / customizations permanent? 

### ISSUE THREAD

**Issue by jacksnodgrass** [bitnami/bitnami-docker-phpbb#47]
issue? question? not sure exactly...  docker/containers are fairly new to me...  I got the docker-compose up to fire off and accessed my new phpbb but ran into some issusses adding a mod.  I wanted to add the adduser mod ( so you could manually add users from the acp ). The instructions were to unpack the .zip file in the ext directory and then use the acp to activate the mod. I used something like "docker exec -ti instance bash" to access my phpbb containter, went to the /opt/something/phpbb/ext directory, got my .zip file there and unzipped it ( I installed unzip and wget in the docker containter to get the mod there ) and I used the ACP to activate it. When I rebooted the container later... phpbb priogram said that the adduser mod was disabled becuase the files were missing. They were no longer in the /opt/..../ext directory where they were installed originally. 

so.. I guess that adding the files the way I did was wrong... what' the correct way to add mods to the container so they will stick around? 

jack

**Comment by carrodher** [comment]
Hi,
Docker’s storage implementation is designed for portability, efficiency and performance. It is optimized for storing, retrieving, and transferring images across different environments. When a container is deleted, all of the data written to the container is deleted along with it.

As a best practice, it is recommended to isolate the data from a container to retain the benefits of adopting containerization. Data management should be distinctly separate from the container lifecycle. There are multiple strategies to add persistence to containers.

In the README file, you can find an example about how to manage the persistence using volumes
https://github.com/bitnami/bitnami-docker-phpbb#persisting-your-application

**Comment by ericblade** [comment]
That's a great explanation of the reason for the problem, but it doesn't address the problem at all, leaving it as an exercise to the user to figure out what you're talking about.

So, ultimately, if you want to persist your extensions even after re-creating the docker volumes, you need to create a volume to store the extensions directory.  Since I'm running in Windows, I use:

      - 'd:\docker\phpbb\ext:/opt/bitnami/phpbb/ext'

add to the volumes configuration in my docker-compose.yml

**Comment by juan131** [comment]
Hi,

@carrodher shared a general explanation about how to use Volumes to persist the data but it didn't address the specific question, you're right @ericblade. Thanks for sharing that solution!
 
@jacksnodgrass could you please confirm you can save your extensions by giving a try to that solution?

**Comment by tompizmor** [comment]
Hi @ericblade, @jacksnodgrass 

I just wanted to mention that this issue should be already fixed in the latest release (Docker tags 3.2.2-ol-7-r27 and 3.2.2-debian-9-r23)

Regards,
Tomas

**Comment by tompizmor** [comment]
There is always a chance that something has changed, especially if you haven't updated the container for a while. I would recommend you to try the new container in an isolated environment and create a backup of your current one. If you are happy with the result, you can upgrade afterward.

**Comment by aleksander351** [comment]
I do not understand why there is a bitnami directory inside the container in root, and then the phpbb data inside opt. And I think I saw the bitnami directory somewhere else as well.

**Comment by tompizmor** [comment]
Hi @aleksander351,

The main installation directory is `/opt/bitnami/phpbb` and you can find all the phpbb files from that directory. 
However, as you said, there is a bitnami folder at root level containing some phpbb data. This is because `/bitnami/phpbb` is the persistent folder used to maintain data between container restarts.
The persisted files can be found also in `/opt/bitnami/phpbb` because they are symlinked to `/bitnami/phpbb`.

```
root@c039f39d8ca2:/bitnami/phpbb# ls -alrth /opt/bitnami/phpbb/
total 600K
-rw-r--r--  1 root   root    12K Sep 13 16:09 ucp.php
-rw-r--r--  1 root   root    56K Sep 13 16:09 search.php
-rw-r--r--  1 root   root   1.1K Sep 13 16:09 report.php
-rw-r--r--  1 root   root    74K Sep 13 16:09 posting.php
-rw-r--r--  1 root   root    54K Sep 13 16:09 memberlist.php
-rw-r--r--  1 root   root   9.0K Sep 13 16:09 mcp.php
-rw-r--r--  1 root   root   8.2K Sep 13 16:09 index.php
-rw-r--r--  1 root   root   1.7K Sep 13 16:09 feed.php
-rw-r--r--  1 root   root    944 Sep 13 16:09 faq.php
-rw-r--r--  1 root   root   2.1K Sep 13 16:09 cron.php
-rw-r--r--  1 root   root   127K Sep 13 16:09 composer.lock
-rw-r--r--  1 root   root   2.0K Sep 13 16:09 composer.json
-rw-r--r--  1 root   root   5.2K Sep 13 16:09 common.php
-rw-r--r--  1 root   root    952 Sep 13 16:09 app.php
-rw-r--r--  1 root   root      0 Sep 13 16:09 .buildcomplete
-rw-r--r--  1 root   root   1.2K Sep 13 16:09 web.config
-rw-r--r--  1 root   root    88K Sep 13 16:09 viewtopic.php
-rw-r--r--  1 root   root    17K Sep 13 16:09 viewonline.php
-rw-r--r--  1 root   root    40K Sep 13 16:09 viewforum.php
drwxr-xr-x  1 root   root   4.0K Nov  2 04:27 ..
drwxr-xr-x  2 root   root   4.0K Nov  2 04:27 licenses
drwxr-xr-x  3 root   root   4.0K Nov  2 04:27 language
drwxr-xr-x  1 root   root   4.0K Nov  2 04:27 includes
drwxr-xr-x  2 root   root   4.0K Nov  2 04:27 download
drwxr-xr-x  3 root   root   4.0K Nov  2 04:27 docs
drwxr-xr-x  1 root   root   4.0K Nov  2 04:27 config
drwxr-xr-x  2 root   root   4.0K Nov  2 04:27 bin
drwxr-xr-x  7 root   root   4.0K Nov  2 04:27 assets
drwxr-xr-x  4 root   root   4.0K Nov  2 04:27 adm
drwxr-xr-x  4 root   root   4.0K Nov  2 04:27 styles
drwxr-xr-x  1 root   root   4.0K Nov  2 04:27 phpbb
drwxr-xr-x 18 root   root   4.0K Nov  2 04:27 vendor
-rw-r-----  1 root   root    148 Nov  5 10:32 .htaccess
drwxr-xr-x  1 daemon daemon 4.0K Nov  5 10:32 cache
lrwxrwxrwx  1 root   root     20 Nov  5 10:32 store -> /bitnami/phpbb/store
lrwxrwxrwx  1 root   root     20 Nov  5 10:32 files -> /bitnami/phpbb/files
lrwxrwxrwx  1 root   root     21 Nov  5 10:32 images -> /bitnami/phpbb/images
lrwxrwxrwx  1 root   root     25 Nov  5 10:32 config.php -> /bitnami/phpbb/config.php
lrwxrwxrwx  1 root   root     18 Nov  5 10:32 ext -> /bitnami/phpbb/ext
drwxr-xr-x  1 root   root   4.0K Nov  5 10:32 .
```

**Comment by aleksander351** [comment]
Ok, so currently, I have my docker-compose file like this:

```
...
volumes:
  - my-phpbb-volume:/bitnami
...
```
and if I want to modify my theme, I go inside `my-phpbb-volume` and upload/modify some files.

Now that does not work, because the container gets its data from /opt/bitnami/phpbb. And when I update my data inside /opt, the changes do get reflected in my running container. But if I restart my container, the changes are lost.

So if I understand correctly, I should bind my volumes like so:
```
...
volumes:
  - my-phpbb-volume:/opt/bitnami/phpbb
...
```
This is different, than in the readme file.
I have not tried it yet, but I presume, if I bind an empty `my-phpbb-volume` with `/opt/bitnami/phpbb`, docker expects my-phpbb-volume pre-populated with all the phpbb data and produces an error?

**Comment by tompizmor** [comment]
```
...
volumes:
  - my-phpbb-volume:/bitnami
...
```

That is the proper way.
What error do you get if you mount the volume like that? I just tried and it worked for me.

**Comment by aleksander351** [comment]
Yes, the theme folder should be persisted, as well as modules, plugins and everything a developer might costumize in a forum. Thanks for the link.

**Comment by tompizmor** [comment]
Hi @aleksander351,

Just wanted to let you know that the latest version of the phpBB container also persists the `styles` folder.
