### ISSUE TITLE
Specify a database name

### ISSUE THREAD

**Issue by julienstroheker** [bitnami/bitnami-docker-phpbb#49]
Hello,

I am curious to understand why there is no possibility to specify a custom name for the database?

Is it make senses to add a `MARIADB_DATABASE` variable ?

In my scenario, I am provisioning a MySQL instance with a dedicated database (Username + Password) and I would like to pass it as variable instead of having a random name like `bitnami_phpbb_BiT5w`

Thanks for the clarification :)

**Comment by juan131** [comment]
Hello @keritaf

I already answered a similar question today: https://github.com/bitnami/bitnami-docker-testlink/issues/55

I think that this option can be interesting on certain scenarios such as the one you described. At this moment, this is not supported since the application would try to create its own database with the format you indicated. This was the first basic approach we develop when we create the Docker Images, but as soon as this image is used on different production scenario we'll find corner cases which are not covered by the current logic.

We could add this feature as we did on WordPress image, what do you think @tompizmor ??

**Comment by juan131** [comment]
Hi everybody

A new revision of the Docker Image (3.2.1-r2 ) hast just been released and now the Bitnami Docker PHPBB Image supports using an existing database.

More info at: https://github.com/bitnami/bitnami-docker-phpbb#use-an-existing-database

Please feel free to use this new image and give us any feedback about this new feature.

**Comment by julienstroheker** [comment]
It seems working on my side :) Thanks @juan131 !

**Comment by ericblade** [comment]
... that's really weird feeling -- there are seperate settings for creating a database and using a database?  what?

**Comment by julienstroheker** [comment]
In my case, I am using a PaaS database (already provisioned) and referring it using the `Use an existing database` settings in the chart.

**Comment by juan131** [comment]
Hi @ericblade 

There are different settings for each case since there are users that do not want to create a database during the initialisation of the containers, they want to use an existing database they already configure on a different platform/service.

**Comment by ericblade** [comment]
... so, you have to specify the create database options, run it, then switch to the use existing database option?  something here is not intuitive.

**Comment by juan131** [comment]
You don't need to use the "Use exiting database option" unless you created your database before (on a previous installation of PHPBB without using Docker for instance or when migrating an existing database). 

If you created the database on the first run of this container solution, it's not necessary to use that option if you persisted the data (PHPBB and MariaDB data) as indicated in the section below:

https://github.com/bitnami/bitnami-docker-phpbb#persisting-your-application
