### ISSUE TITLE
Unable to enable opcache.

### ISSUE THREAD

**Issue by penM000** [bitnami/bitnami-docker-phpbb#59]
**Description**
Even if /opt/bitnami/php/etc/php.ini is mounted locally by docker, "opcache.enable = Off" is added at the end of the configuration file.

**Steps to reproduce the issue:**

1. [First Step]
Copy the current php.ini from the container to the host, add "opcache.enable = 1" and save.

2. [Second Step]
Mount php.ini on the container with docker's local mount.
path
./php.ini:/usr/local/etc/php/php.ini
3. [and so on...]

It is added as follows.
host php.ini
```
upload_max_filesize = 40M
post_max_size = 40M
extension_dir = /opt/bitnami/php/lib/php/extensions
date.timezone = UTC
zend_extension = opcache.so
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 60
opcache.fast_shutdown = 1
opcache.interned_strings_buffer = 16
opcache.memory_consumption = 192
opcache.file_cache = /opt/bitnami/php/tmp/opcache_file
opcache.enable = 1
```
container php.ini
```
upload_max_filesize = 40M
post_max_size = 40M
extension_dir = /opt/bitnami/php/lib/php/extensions
date.timezone = UTC
zend_extension = opcache.so
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 60
opcache.fast_shutdown = 1
opcache.interned_strings_buffer = 16
opcache.memory_consumption = 192
opcache.file_cache = /opt/bitnami/php/tmp/opcache_file
opcache.enable = 1
opcache.enable = Off
```
How can this be enabled for cache?
Can you please give me information on that?

**Comment by rafariossaa** [comment]
Hi, @penM000 
  This was disable because it was producing issues in the past.
  I am going to create a internal task to re-test this again and change the behavior if it is ok. 

  Meanwhile you can try with these steps:
  - Run it by default
  - Enter into the container and change the value
  - Exit the container and make an image of the modified container (docker commit)
  - Tag the new image
  - Modify docker-compose with the new tag for phpbb.

  We will come back as son as we have news.

**Comment by penM000** [comment]
Thank you for teaching me.
I will customize the container.

**Comment by rafariossaa** [comment]
Hi @penM000,
  You are welcome.
  I am closing this issue, if you find another one, please don't hesitate to open it.
